Roundabout
ll7/psaf2 pull request #100
Opened 2021-03-26 18:29 UTC by luk-ha

2021-03-27 11:48 UTC, jubra97 requested changes
Bitt Dokus von planner (local/global) anpassen!

2021-03-27 11:48 UTC, jubra97 commented on Perception/road_features/src/road_features/road_features.py
> +            self.roundabout_pub.publish(roundabout_msg)
wenn ihr nahe am kreisverlehr seid published ihr keinen lane_status mehr oder?

2021-03-27 11:48 UTC, jubra97 commented on Perception/road_features/src/road_features/road_features.py
> +                distance = self.lanelet_lengths[current_lanelet_id][-1] - self.lanelet_lengths[current_lanelet_id][idx]
Wird nicht verwendet oder?

2021-03-27 11:48 UTC, jubra97 commented on Planning/global_planner/src/global_planner/global_planner_commonroad.py
> +        self.lanelet_ids_roundabout_inside = [190, 191, 196, 306, 308, 305, 307, 198, 201, 202, 199, 195, 188, 193]
nur für map 3 denke das kann sonst auf anderen maps probleme machen
Bedingung für self.map_number == ? stimmt aber noch nicht: bei world_info_received müsste stehen: self.map_number = int(msg.map_name[-1])

2021-03-27 11:48 UTC, jubra97 commented on Planning/local_planner/src/local_planner/local_planner_commonroad.py
> +                elif approach_roundabout:
bitte in eigene Funktion
Auskommentierter Code ganz raus; gerne noch ein paar mehr Kommentare

2021-03-27 11:48 UTC, jubra97 commented on Planning/local_planner/src/local_planner/local_planner_commonroad.py
> +                            return
return True oder return False, sosnt stürzt BT ab

2021-03-27 11:48 UTC, jubra97 commented on Planning/local_planner/src/local_planner/local_planner_commonroad.py
> +                            inner_lane = self.scenario.lanelet_network.find_lanelet_by_id(inner_lanelet_id)
inner_lane: nicht besser "outer_lane"?

2021-03-27 11:48 UTC, jubra97 commented on Planning/local_planner/src/local_planner/local_planner_commonroad.py
> +                                    if minimum > 2:
kommentare hier wären gut

2021-03-27 11:48 UTC, jubra97 commented on Planning/behavior_agent/src/behavior_agent/behaviours/road_features.py
> +            rospy.loginfo(f"distance to roundabout in road_features = {dist}")
Der Log noch raus

2021-03-28 06:36 UTC, Wollator commented on Perception/road_features/src/road_features/road_features.py
> +            self.roundabout_pub.publish(roundabout_msg)
wird jetzt wieder mit gepublished

2021-03-28 06:40 UTC, Wollator commented on Planning/global_planner/src/global_planner/global_planner_commonroad.py
> +        self.lanelet_ids_roundabout_inside = [190, 191, 196, 306, 308, 305, 307, 198, 201, 202, 199, 195, 188, 193]
ja, stimmt 
wurde geändert

2021-03-28 06:42 UTC, Wollator commented on Planning/local_planner/src/local_planner/local_planner_commonroad.py
> +                            return
erledigt

2021-03-28 06:44 UTC, Wollator commented on Planning/local_planner/src/local_planner/local_planner_commonroad.py
> +                            inner_lane = self.scenario.lanelet_network.find_lanelet_by_id(inner_lanelet_id)
joa

2021-03-28 07:00 UTC, Wollator commented on Planning/local_planner/src/local_planner/local_planner_commonroad.py
> +                elif approach_roundabout:
ist jetzt in eigener Funktion

2021-03-28 09:11 UTC, luk-ha commented
> Bitt Dokus von planner (local/global) anpassen!

erledigt

2021-03-28 14:30 UTC, jubra97 approved these changes

2021-03-28 14:30 UTC, merged