Street sign detector
ll7/psaf2 pull request #55
Opened 2021-01-22 17:05 UTC by maurizio-v

2021-01-22 17:07 UTC, faeibson commented
Alle Files im Package-Ordner sind relevant, außer im Unterordner darknet, hier wurden nur die darknet.py und darknet_carla.py ein wenig verändert.

2021-01-22 23:16 UTC, halentin submitted a review, later dismissed
Hab mir jetzt erstmal nur das street_sign_detector.py file vorgenommen. Ich hab echt Schwierigkeiten zu unterscheiden was nun zu darknet gehört, was vom Praktikum letztes Jahr übernommen ist, und was ihr selber geschrieben habt. Vielleicht könnt ihr den PR noch aufteilen. Julius hat für Commonroads so ein Git-Submodul eingerichtet, das bei der Installation mitgeklont wird. Wäre das für Darknet auch eine Variante?

2021-01-22 23:16 UTC, halentin commented on Perception/street_sign_detector/src/street_sign_detector/street_sign_detector.py
> +                if pixel[0] > 0 and img_sem[pixel[0] - 1, pixel[1], 0] == 0 and img_sem[pixel[0] - 1, pixel[1], 1] == 220 and img_sem[pixel[0] - 1, pixel[1], 2] == 220:
Ich würde sogar vorschlagen die Farbe noch als Variable festzulegen um magic numbers zu vermeiden
```suggestion
                if pixel[0] > 0 and (img_sem[pixel[0] - 1, pixel[1]] == [0,220,220]).all():
```

2021-01-22 23:16 UTC, halentin commented on Perception/street_sign_detector/src/street_sign_detector/street_sign_detector.py
> +                    img_sem[pixel[0] - 1, pixel[1], 2] = 255
```suggestion
                    img_sem[pixel[0] - 1, pixel[1]] = [255, 255,255]
```
analog zu oben

2021-01-22 23:16 UTC, halentin commented on Perception/street_sign_detector/src/street_sign_detector/street_sign_detector.py
> +                (pixel[0] * 2 + 1), (pixel[1] * 2 + 1), 0]
Das sollte wahrscheinlich ein Einzeiler sein.

2021-01-22 23:16 UTC, halentin commented on Perception/street_sign_detector/src/street_sign_detector/street_sign_detector.py
> +        # resolution is two times the resolution of the semantic segmentation camera)
Diese Annahme macht es problematisch an den Kameraeinstellungen später etwas zu ändern. Vlt könnte man einfach anhand der Kameragrößen skalieren?

2021-01-22 23:16 UTC, halentin commented on Perception/street_sign_detector/src/street_sign_detector/street_sign_detector.py
> +        self.global_filename_counter += 1
sollte das auskommentiert sein?

2021-01-22 23:16 UTC, halentin commented on Perception/street_sign_detector/src/street_sign_detector/street_sign_detector.py
> +                    img_sem[h, w, 2] = 255
siehe oben

2021-01-22 23:16 UTC, halentin commented on Perception/street_sign_detector/src/street_sign_detector/street_sign_detector.py
> +    rospy.init_node('vehicle_control', anonymous=True)
```suggestion
    rospy.init_node('street_sign_detector', anonymous=True)
```

2021-01-22 23:16 UTC, halentin commented on Perception/street_sign_detector/src/street_sign_detector/street_sign_detector.py
> +from carla_msgs.msg import CarlaEgoVehicleControl
```suggestion

```

2021-01-22 23:16 UTC, halentin commented on Perception/street_sign_detector/src/street_sign_detector/street_sign_detector.py
> +        self._control = CarlaEgoVehicleControl()
```suggestion

```

2021-01-22 23:16 UTC, halentin commented on Perception/street_sign_detector/src/street_sign_detector/street_sign_detector.py
> +        self.global_filename_counter = 0
sollte das auskommentiert sein?

2021-01-22 23:16 UTC, halentin commented on Perception/street_sign_detector/src/street_sign_detector/street_sign_detector.py
> +    def get_block_by_pixel(self, img_rgb, img_sem, h_current, w_current, height, width, filename):
Diese Funktion hat ca. 160 Zeilen, und enthält einerseits Processing für die Semantic Segmentation und andererseits Code für die YOLO Detection.  Prinzipiell würde ich Funktionen schreiben, die nur genau eine Aufgabe erfüllen. Bei allem über 20 Codezeilen würde ich darüber nachdenken, ob es keine sinnvollere Aufteilung gibt. Außerdem würde vorschlagen diese Funktionen in unterschiedliche Dateien aufzuteilen, vorallem weil der Semantic-Extraction Code an dieser Stelle (soweit ich das verstehe) nicht verwendet wird. 
Generell ist mir aufgefallen, dass viele Codezeilen wiederholt werden. Das ist für Änderungen und für Lesbarkeit sehr ungünstig. Wo ich direkt eine Idee hatte habe ich Verbesserungsvorschläge eingefügt. Das sind aber längst nicht alle Stellen an denen noch Einsparungspotenzial bestünde.

2021-01-27 00:40 UTC, faeibson commented on Perception/street_sign_detector/src/street_sign_detector/street_sign_detector.py
> +                if pixel[0] > 0 and img_sem[pixel[0] - 1, pixel[1], 0] == 0 and img_sem[pixel[0] - 1, pixel[1], 1] == 220 and img_sem[pixel[0] - 1, pixel[1], 2] == 220:
variablen eingeführt und die ganze logik wird gerade insgesamt überdacht

2021-01-27 00:42 UTC, faeibson commented on Perception/street_sign_detector/src/street_sign_detector/street_sign_detector.py
> +        # resolution is two times the resolution of the semantic segmentation camera)
tatsächliche Kameraauflösungen werden jetzt von den Topics geholt, Anpassung des Mappings fehlt noch

2021-01-27 00:42 UTC, faeibson commented on Perception/street_sign_detector/src/street_sign_detector/street_sign_detector.py
> +        self.global_filename_counter += 1
zumindest ein debug Flag einzuführen hat nicht geschadet 👍

2021-01-27 00:44 UTC, faeibson commented on Perception/street_sign_detector/src/street_sign_detector/street_sign_detector.py
> +        self.global_filename_counter = 0
nicht ganz, aber es gehört zum debug part, ist jetzt übersichtlicher denke ich

2021-01-27 00:46 UTC, faeibson commented on Perception/street_sign_detector/src/street_sign_detector/street_sign_detector.py
> +    def get_block_by_pixel(self, img_rgb, img_sem, h_current, w_current, height, width, filename):
da hast du vollkommen recht, die funktion ist jetzt auf mehrere funktionen aufgeteilt. werden noch weiter drüberschauen, die logik wird sich mit den erweiterungen jetzt noch verändern und da wird sicher noch genug anfallen

2021-01-27 01:08 UTC, faeibson commented on Perception/street_sign_detector/src/street_sign_detector/street_sign_detector.py
> +    def get_block_by_pixel(self, img_rgb, img_sem, h_current, w_current, height, width, filename):
Achja, von letztem Jahr ist die darknet_carla.py übernommen und ansonsten nur 1-2 Schnipsel wie das Mappen des Prediction-Objekts von YOLO auf eine PerceptionInfo Instanz. Und die PerceptionInfo msg selbst ist auch übernommen.
Das YOLO/Darknet ist jetzt als Submodul eingerichtet, entsprechende Infos dazu sind in der Readme. Die Config des Netzes und die Weights haben wir bis jetzt auch vom letzten Jahr übernommen. Mal schauen, ob wir das so lassen (können).

2021-03-13 15:37 UTC, jubra97 requested changes
Lief sehr langsam, vorallem auf Performance Verbesserungen setzen. Vorschläge zur Schelifenvermeidung befinden sich im Code. Leider ist Code auf OpenCV/NumPy fast immer schneller als eigener.
Code-Doku passt, Readme gerne ausführlicher.

2021-03-13 15:37 UTC, jubra97 commented on Perception/street_object_detector/readme.md
> +Uses the semantic segmentation and rgb cameras to detect street objects (street signs, traffic lights) in the current view.
Ausführlicher, da auch Doku. Z.b kurze Erklärung wie vorgegangen wird + implementierte Funktionen

2021-03-13 15:37 UTC, jubra97 commented on Perception/street_object_detector/src/street_object_detector/street_object_detector.py
> +        self.speed_limit_values = [ '30', '60', '90' ]
GIbts wirklich nur die 3 (in allen Karten)?

2021-03-13 15:37 UTC, jubra97 commented on Perception/street_object_detector/src/street_object_detector/street_object_detector.py
> +        stop_img = np.zeros((height, width, channels), np.uint8)
wird nicht genutzt

2021-03-13 15:37 UTC, jubra97 commented on Perception/street_object_detector/src/street_object_detector/street_object_detector.py
> +        for color_key in self.semantic_segment_search_colors.keys():
Ist es nicht effizienter sich zuerst jeweils eine Maske für jede benötigte Farbe der Semantic Segmentation zu bilden und dann auf dieser zu arbeiten. Das geht sicher mit OpenCv/Numpy und man benötigt keine Schleife(n).

2021-03-13 15:37 UTC, jubra97 commented on Perception/street_object_detector/src/street_object_detector/street_object_detector.py
> +    def get_block_by_pixel(self, img_rgb, img_sem, search_color, h_current, w_current, border_height):
Ist ein standard Problem, da gibt es schon sehr effiziente Lösungen.
https://docs.opencv.org/3.1.0/d3/dc0/group__imgproc__shape.html#gac2718a64ade63475425558aa669a943a
https://en.wikipedia.org/wiki/Connected-component_labeling

2021-03-13 15:37 UTC, jubra97 commented on Perception/street_object_detector/src/street_object_detector/street_object_detector.py
> +
Hier werden sehr viele Schleifen in einander gechachtelt.

2021-03-13 15:37 UTC, jubra97 commented on Perception/street_object_detector/src/street_object_detector/traffic_light_recognition.py
> +import cv2
warum in extra file? Oder das davor auch auf mehrere Files aufteilen.

2021-03-13 15:37 UTC, jubra97 commented on Perception/street_object_detector/src/street_object_detector/street_object_detector.py
> +        r = rospy.Rate(2)
Vielleicht geht dann auch eine höhere Frequenz

2021-03-17 21:46 UTC, faeibson commented on Perception/street_object_detector/readme.md
> +Uses the semantic segmentation and rgb cameras to detect street objects (street signs, traffic lights) in the current view.
danke, haben nachgebessert

2021-03-17 21:46 UTC, faeibson commented on Perception/street_object_detector/src/street_object_detector/street_object_detector.py
> +        self.speed_limit_values = [ '30', '60', '90' ]
ja

2021-03-17 21:46 UTC, faeibson commented on Perception/street_object_detector/src/street_object_detector/street_object_detector.py
> +        stop_img = np.zeros((height, width, channels), np.uint8)
danke!

2021-03-17 21:48 UTC, faeibson commented on Perception/street_object_detector/src/street_object_detector/street_object_detector.py
> +        for color_key in self.semantic_segment_search_colors.keys():
haben uns jetzt noch ewig damit beschäftigt, aber am ende lief es gefühl nur noch schlechter. haben unseren code im endeffekt trotzdem noch optimiert bekommen, indem wir die semantic segmentation nicht hochskalieren sondern auf dem kleinen bild bleiben und die ergebnisse erst ganz am ende mit scale factors und offsets anpassen. außerdem explizit auf np arrays geachtet, läuft jetzt auf jeden fall gut.

2021-03-17 21:48 UTC, faeibson commented on Perception/street_object_detector/src/street_object_detector/street_object_detector.py
> +    def get_block_by_pixel(self, img_rgb, img_sem, search_color, h_current, w_current, border_height):
s.o. wir habens versucht aber lief leider echt nicht gut.

2021-03-17 21:49 UTC, faeibson commented on Perception/street_object_detector/src/street_object_detector/street_object_detector.py
> +
haben wir optimiert

2021-03-17 21:49 UTC, faeibson commented on Perception/street_object_detector/src/street_object_detector/traffic_light_recognition.py
> +import cv2
erledigt

2021-03-17 21:49 UTC, faeibson commented on Perception/street_object_detector/src/street_object_detector/street_object_detector.py
> +        r = rospy.Rate(2)
mit 5 läufts jetzt auch gut

2021-03-18 09:07 UTC, jubra97 approved these changes

2021-03-18 09:07 UTC, merged