added slowed by car in front detection from radar
ll7/psaf2 pull request #74
Opened 2021-02-28 13:33 UTC by halentin

2021-02-28 18:24 UTC, jubra97 requested changes

2021-02-28 18:24 UTC, jubra97 commented on Planning/behavior_agent/src/behavior_agent/behaviours/topics2blackboard.py
> +            {'name':f"/psaf/{role_name}/distance", 'msg':Float64, 'clearing-policy': py_trees.common.ClearingPolicy.NEVER},
Hast du den letzten main gepullt gehabt? Sollte das nicht distance_to_next_intersection sein?

2021-03-01 06:52 UTC, Wollator requested changes

2021-03-01 06:52 UTC, Wollator commented on Perception/radar/src/radar/radar.py
> +            self._slowed_publisher.publish(True)
hier wird slowed_publisher auch true gepublished, wenn er ein Auto bzw. ein Gegenstand sieht, was aber noch weit genug weg ist oder?

2021-03-02 07:18 UTC, halentin commented on Perception/radar/src/radar/radar.py
> +            self._slowed_publisher.publish(True)
Jo das siehst du richtig, aber das ist Absicht. Er soll versuchen die Spur zu wechseln, sobald jemand vor ihm auftaucht. Das maximiert die Chancen, dass das mit dem überholen klappt. Falls das später Probleme macht ändern wir es nochmal, aber fürs erste erschien mir die Lösung erstmal sinnvoll.

2021-03-03 09:45 UTC, jubra97 approved these changes

2021-03-03 09:45 UTC, Wollator approved these changes

2021-03-03 09:46 UTC, merged