Get other traffic
ll7/psaf2 pull request #79
Opened 2021-03-12 15:56 UTC by Wollator

2021-03-13 12:54 UTC, jubra97 requested changes
Einbau in den behaviour tree fehlt noch.

2021-03-13 12:54 UTC, jubra97 commented on Perception/lidar/src/lidar/lidar.py
> +        self.org_scenario = copy.deepcopy(self.scenario)
deepcopy witd nicht gebraucht

2021-03-13 12:54 UTC, jubra97 commented on Perception/lidar/src/lidar/lidar.py
> +    def __init__(self, role_name, target_speed, args_longitudinal=None, args_lateral=None):
alle variablen rauswerfen die nicht genutzt werden

2021-03-13 12:54 UTC, jubra97 commented on Perception/lidar/src/lidar/lidar.py
> +class Lidar(object):  # pylint: disable=too-few-public-methods
Klassenbeschreibung anpassen

2021-03-13 12:54 UTC, jubra97 commented on Perception/lidar/src/lidar/lidar.py
> +    def get_right_and_left_lanelet(self):
Sollen nur Spuren, die die gleiche Fahrtrichtung haben betrachtet werden? Wenn ja gibts nach meinem pull reqeust eine message die genau die enthält. Das kann man aber denke danach auch noch einfach umbauen.

2021-03-13 12:54 UTC, jubra97 commented on Perception/lidar/src/lidar/lidar.py
> +                self.obstacle_on_left_lane_pub.publish("ObstacleLeft")
nicht sinnvoller die Distanz zum nächsten Fahrzeug zu publishen? Dann kann man das evtl. noch später verarbeiten

2021-03-14 16:41 UTC, luk-ha commented on Perception/lidar/readme.md
> +## About
Anpassen oder rauswerfen

2021-03-14 16:41 UTC, luk-ha commented on Perception/lidar/src/lidar/lidar.py
> +        # self._dist_publisher = rospy.Publisher(f"psaf/{role_name}/radar/distance", Float64, queue_size=1)
kann das raus?

2021-03-18 07:52 UTC, Wollator reviewed
Distanz publishen können wir ja gleich diskutieren

2021-03-24 16:48 UTC, luk-ha commented on Acting/ego_vehicle/launch/ego_vehicle.launch
> +  <include file="$(find lidar)/launch/lidar.launch"> </include>
wieso zweimal?

2021-03-24 16:48 UTC, luk-ha commented on Perception/lidar/src/lidar/lidar.py
> +        if self.left_lanelet != None:
besser wäre "is not" anstatt von !=

2021-03-24 16:48 UTC, luk-ha commented on Perception/lidar/src/lidar/lidar.py
> +        if self.right_lanelet != None:
besser is not

2021-03-24 16:48 UTC, luk-ha commented on Planning/behavior_agent/src/behavior_agent/behaviours/traffic_objects.py
> +        elif self.car_left.data > 20 or self.car_left.data is None:
würde die Reihenfolge der bedingugen vertauschen

2021-03-24 16:48 UTC, luk-ha commented on Planning/behavior_agent/src/behavior_agent/behaviours/traffic_objects.py
> +        elif self.car_right.data > 20 or self.car_right.data is None:
reihenfolge

2021-03-24 16:48 UTC, luk-ha commented on Test_Scenarios/ego_vehicle_spawn_distance.sh
> +>>>>>>> changed .sh
hier könnte man die merge dinge noch lösen

2021-03-24 16:55 UTC, Wollator commented on Acting/ego_vehicle/launch/ego_vehicle.launch
> +  <include file="$(find lidar)/launch/lidar.launch"> </include>
was meinst du genau? 
radar wird hier ja einmal gelöscht und unten eingefügt

2021-03-24 17:01 UTC, luk-ha commented on Acting/ego_vehicle/launch/ego_vehicle.launch
> +  <include file="$(find lidar)/launch/lidar.launch"> </include>
hab mich verschaut, sorry

2021-03-24 18:23 UTC, luk-ha approved these changes

2021-03-24 20:00 UTC, jubra97 approved these changes

2021-03-24 20:00 UTC, merged