Stop lines
ll7/psaf2 pull request #80
Opened 2021-03-14 14:46 UTC by luk-ha

2021-03-14 17:04 UTC, halentin requested changes
Bitte Readme ergänzen, und Package entsprechend der neuen Verwendung umbennen (oder einfach line-detection).

2021-03-14 17:04 UTC, halentin commented on Planning/behavior_agent/src/behavior_agent/behaviours/intersection.py
> +from datetime import datetime
Ich fände hier rospy.Time besser. Da ist es nämlich egal, ob die Simulation langsam oder schnell läuft, ob im synchronen oder asynchronen Modus etc

2021-03-14 17:04 UTC, halentin commented on Planning/behavior_agent/src/behavior_agent/behaviours/intersection.py
>      def update(self):
Wenn ich den Code richtig verstehe, halten wir nur an, wenn es auch tatsächlich eine Stoplinie gibt. Kann das nicht ein Problem werden wenn es keine gibt (oder die Perception fehlschlägt?).

2021-03-14 17:04 UTC, halentin commented on Acting/ego_vehicle/config/sensors.json
> +            "image_size_y": 300,
Größe und Form der Semantic Kamera nochmal mit Mauri, Fabi und Yulia abstimmen!

2021-03-14 17:04 UTC, halentin commented on Perception/lane_detection/src/lane_detection/lane_detection.py
> +            self.imgwidth = 400
Größe und Form der Semantic Kamera nochmal mit Mauri, Fabi und Yulia abstimmen!

2021-03-14 20:32 UTC, luk-ha commented on Planning/behavior_agent/src/behavior_agent/behaviours/intersection.py
>      def update(self):
Julius und ich haben gemeint wenn's keine Stoplinie gibt haben wir eh Vorfahrt müssen also auch nicht anhalten und bisher bestätigen meine Beobachtungen das.

2021-03-15 13:40 UTC, luk-ha commented
> Bitte Readme ergänzen, und Package entsprechend der neuen Verwendung umbennen (oder einfach line-detection).

erledigt

2021-03-15 22:12 UTC, halentin approved these changes

2021-03-16 14:13 UTC, merged