Separates traffic light topic für erkannte Ampeln hinzugefügt
ll7/psaf2 pull request #82
Opened 2021-03-20 12:45 UTC by maurizio-v

2021-03-21 13:35 UTC, halentin commented on Acting/ego_vehicle/config/sensors.json
> +			"image_size_y": 70,
Versehen oder Absicht? line-detection braucht die größere SemSeg

2021-03-21 15:26 UTC, maurizio-v commented on Acting/ego_vehicle/config/sensors.json
> +			"image_size_y": 70,
Ist Absicht. Ich hab eine zweite Sem Seg zu den Sensoren hinzugefügt (id front_flat). Die Sem Seg, die von der line detection benutzt wird hat die id "front" und sollte noch nach wie vor laufen.

2021-03-21 15:32 UTC, halentin commented on Acting/ego_vehicle/config/sensors.json
> +			"image_size_y": 70,
dann hab ich nichts gesagt :)

2021-03-22 02:48 UTC, maurizio-v commented
Wir haben nur noch ein paar Änderungen an der Größe der semantic segmentation Kamera gemacht und ein paar Parameterwerte verändert. Außerdem die Farbmasken für die Ampelerkennung angepasst.

2021-03-22 12:28 UTC, jubra97 requested changes

2021-03-22 12:28 UTC, jubra97 commented on Perception/street_object_detector/src/street_object_detector/street_object_detector.py
> +            cv2.waitKey(1)
Debug überbleibsel?

2021-03-22 14:09 UTC, maurizio-v commented on Perception/street_object_detector/src/street_object_detector/street_object_detector.py
> +            cv2.waitKey(1)
Ist entfernt

2021-03-22 15:49 UTC, jubra97 approved these changes

2021-03-22 15:49 UTC, merged