Integrate street object detector
ll7/psaf2 pull request #98
Opened 2021-03-24 11:32 UTC by jubra97

2021-03-24 13:37 UTC, luk-ha requested changes

2021-03-24 13:37 UTC, luk-ha commented on Planning/behavior_agent/src/behavior_agent/behaviours/intersection.py
> +        if self.stopline_detected and self.stopline_distance != np.inf or light_status == "":
nach unten

2021-03-24 13:37 UTC, luk-ha commented on Planning/behavior_agent/src/behavior_agent/behaviours/intersection.py
> +        elif self.stopline_detected and self.stopline_distance != np.inf:
müsste hier nicht noch eine Überprüfung auf die Ampelfarbe erfolgen? weil im Fall Stopline detected , speed noch bei 30, stopline_distance = 0.8 und ampel rot wird hier doch success zurückgegeben und damit fahren wir weiter (weil als speed wird 30 *0.8 gepublisht) und somit über die Linie

2021-03-25 09:16 UTC, halentin commented on Planning/behavior_agent/src/behavior_agent/behaviours/intersection.py
> +        elif self.stopline_detected and self.stopline_distance != np.inf:
Hab jetzt nochmal lange drüber nachgedacht, aber ich verstehe es glaube noch nicht. Success wird nur zurückgegeben, wenn wir a) über die Linie sind,  oder b) stehen. Im Fall a) wird bei roter Ampel in jedem Fall als letztes 0 gepublished bevor wir success zurückgeben (Zeile 61)
Hast du das Problem schonmal nachgestellt?

2021-03-25 09:20 UTC, jubra97 commented on Planning/behavior_agent/src/behavior_agent/behaviours/intersection.py
> +        elif self.stopline_detected and self.stopline_distance != np.inf:
Ich bin mir gerade auch nicht ganz sicher obs passt, wenn wir über der Linie sind ist ja selt.stopline_distance eigentlich  = np.inf und !=. Ich würde das später bei mir nochmal ausprobieren!

2021-03-29 12:06 UTC, closed without merging